### ISSUE TITLE
Create a more complete contributions guidelines

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#17]
Right now, the contributions guidelines focus on code, but there are so much more one can do to contribute to MeiliSearch, like helping with the documentation, writing blog post, speaking at conference, and more...

- [x] [Add details to contribution information (core, integrations & tools)](https://github.com/meilisearch/devrel/issues/121)
- [ ] [Create documentation on issues contributions](https://github.com/meilisearch/devrel/issues/122)
- [x] [Create PR documentation on contributions](https://github.com/meilisearch/devrel/issues/123)
- [x] [Integrate the contribution information into the documentation site](https://github.com/meilisearch/devrel/issues/124)

**Comment by fharper** [comment]
Once done, we will have a kind of tl;dr in all the contributions.md files that will point to the documentation. @react-learner you can start thinking where it will fit in the doc reorg.

**Comment by fharper** [comment]
Comments from @curquiza are at https://github.com/meilisearch/devrel/issues/159

**Comment by ferdi05** [comment]
as #121 #123 #124 are closed, this becomes a duplicate of #122 which is a duplicate of #309, so I'm closing it to keep only #309 open
