### ISSUE TITLE
Review all the unanswered items in GitHub Discussions

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#57]
Select answer for all unanswered questions or answer if none given.

**Comment by fharper** [comment]
@CaroFG we should review all the messages in Discussions and check the one without an answer to either select the right answer (will add the green checkmark) or answer them. If we don't know the answer, let's check with the right team/person to either help us or answer it themselves. The goal is to have all of those answered :D

**Comment by CaroFG** [comment]
So I don't know if I have the power to add the green checkmark since I don't see an option to do that. I just went through all the unanswered ones and made a list of the true unanswered questions (oldest to newest)

- [ ] Queue doubts #854
- [ ] How to set ranking rules only contain keywords #893
- [ ] Lengthy indexing time. 3 days? #892
- [ ] Is it possible enable CORS? #1002
- [ ] Does MeiliSearch has fuzzy queries? #1096
- [ ] Cheapest way to host a MeiliSearch instance #1162

**Comment by fharper** [comment]
@CaroFG : you should have access now. I'll share with you some ideas on how to respond to older questions later today.

**Comment by fharper** [comment]
So, on question older than two weeks, if you cannot answer the question with the data you have from the OP, you can write something like "Sorry for the delay in answering your questions. Were you able to fix it?" If yes, close the issue, if not, obviously, let's help the person.

In the cases when you can answer the question, it's good to do it so it becomes a knowledge base and people can find the answer to a question similar to theirs before posting a new one. So in that case, again, apologize, and add the answer.

Make those responds your own style.

**Comment by CaroFG** [comment]
Thank you @fharper What should we do with this kind of question? https://github.com/meilisearch/MeiliSearch/discussions/1003  The author managed to make it work with curl but not homebrew, which was his problem in the first place...

**Comment by fharper** [comment]
I will skip this one for now since they solved their issues, and it may be really specific to their computer. In the case it's a common error we see, I would answer it.

**Comment by fharper** [comment]
Only one left @CaroFG  :D

**Comment by fharper** [comment]
I replied, so it's now active again, I'm closing this issue.
